# Generated by Django 2.1.5 on 2019-01-24 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.EmailField(max_length=254)),
                ('destination', models.CharField(max_length=100)),
                ('passenger_number', models.IntegerField()),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_allowed', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('special', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('special', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='rides',
            name='passengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
