# Generated by Django 2.1.5 on 2019-01-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('passenger_number', models.IntegerField()),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_allowed', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('special', models.TextField(blank=True)),
                ('driver', models.CharField(max_length=100)),
                ('passengers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Driver', 'Driver'), ('Sharer', 'Sharer'), ('Owner', 'Owner')], max_length=10)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SharerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('passenger_number', models.IntegerField()),
                ('earliest_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sharer', '-earliest_time'),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
                ('plate_number', models.CharField(max_length=150)),
                ('special', models.TextField(blank=True)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('driver',),
            },
        ),
        migrations.AddField(
            model_name='rides',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RideApp.RideStatus'),
        ),
    ]
