# Generated by Django 2.1.5 on 2019-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='owner_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rides',
            name='sharer_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rides',
            name='passenger_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Sharer', 'Sharer'), ('Owner', 'Owner'), ('Driver', 'Driver')], max_length=10),
        ),
    ]
