# Generated by Django 2.1.5 on 2019-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Driver', 'Driver'), ('Sharer', 'Sharer')], max_length=10),
        ),
    ]
