# Generated by Django 2.1.5 on 2019-01-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Sharer', 'Sharer'), ('Owner', 'Owner')], max_length=10),
        ),
    ]
