# Generated by Django 2.1.5 on 2019-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0002_auto_20190127_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='special',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Sharer', 'Sharer'), ('Owner', 'Owner'), ('Driver', 'Driver')], max_length=10),
        ),
    ]
