# Generated by Django 2.1.5 on 2019-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0002_auto_20190204_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='owner_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rides',
            name='sharer_number',
            field=models.IntegerField(default=0),
        ),
    ]
