# Generated by Django 2.1.5 on 2019-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0004_auto_20190127_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Owner', 'Owner'), ('Sharer', 'Sharer')], max_length=10),
        ),
    ]
