# Generated by Django 2.1.5 on 2019-01-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0005_auto_20190127_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Sharer', 'Sharer'), ('Owner', 'Owner')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='special',
            field=models.TextField(blank=True),
        ),
    ]
