# Generated by Django 2.1.5 on 2019-02-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0006_auto_20190202_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Sharer', 'Sharer'), ('Driver', 'Driver')], max_length=10),
        ),
    ]
