# Generated by Django 2.1.5 on 2019-02-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0008_auto_20190205_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Sharer', 'Sharer'), ('Driver', 'Driver'), ('Owner', 'Owner')], max_length=10),
        ),
    ]
