# Generated by Django 2.1.5 on 2019-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0009_auto_20190128_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Sharer', 'Sharer'), ('Driver', 'Driver'), ('Owner', 'Owner')], max_length=10),
        ),
    ]
