# Generated by Django 2.1.5 on 2019-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideApp', '0016_auto_20190128_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Sharer', 'Sharer'), ('Owner', 'Owner'), ('Driver', 'Driver')], max_length=10),
        ),
    ]
